---
- name: Setup local environment
  hosts: localhost
  connection: local

  vars:
    packages:
      - bat
      - cargo
      - dconf
      - gh
      - make
      - neovim
      - ripgrep
      - ruff
      - rustc
      - stow
      - tmux
      - uv

  tasks:
    - name: Ensure packages are installed
      become: true
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present

    - name: Ensure dotfiles are linked
      changed_when: false
      ansible.builtin.command:
        chdir: files
        cmd: make

    - name: Ensure neovim plugin manager is installed
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: "0644"

    - name: Ensure neovim plugins are installed
      changed_when: false
      ansible.builtin.command:
        cmd: "nvim +PlugUpgrade +PlugUpdate +PlugClean! +qall"
