---
- name: Setup local environment
  hosts: localhost
  connection: local

  vars:
    packages:
      # sorted alphabetically
      - bat
      - eza
      - fd
      - gh
      - go
      - ipython
      - jq
      - make
      - neovim
      - node
      - nox
      - podman
      - pre-commit
      - ruff
      - rust
      - stow
      - tmux
      - uv
      - wget

  tasks:
    - name: Ensure packages are installed
      community.general.homebrew:
        name: "{{ packages }}"
        state: present

    - name: Ensure dotfiles are linked
      changed_when: false
      ansible.builtin.command:
        chdir: files
        cmd: make

    - name: Ensure neovim plugin manager is installed
      changed_when: false
      ansible.builtin.command:
        cmd: sh -c 'curl -fLo "$HOME/.local/share/nvim/site/autoload/plug.vim" \
          --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - name: Ensure neovim plugins are installed
      changed_when: false
      ansible.builtin.command:
        cmd: "nvim +PlugUpgrade +PlugUpdate +PlugClean! +qall"
